### ISSUE TITLE
Second query getting values from the first query

### ISSUE THREAD

**Issue by krstivoja** [ryanwelcher/advanced-query-loop#29] opened 2023-10-01 20:35 UTC
Hello. This is a great plugin but I am getting bug on the front end only. 

I am having 2 custom queries on the static homepage.

1st query is Easy Digital Downloads products
2nd query is CPT Testimonials. 

In the editor everything works fine but on the front end in the 2nd query I am getting loop from the first one. 

Please check the screenshoot as well.

Did you maybe forgot to reset query?

<img width="3008" alt="Screenshot 2023-10-01 at 22 29 26" src="https://github.com/ryanwelcher/advanced-query-loop/assets/1234350/408af8c1-1c1d-444d-a23a-0ba10b47cf88">

**Comment by ryanwelcher** [comment] 2023-10-24 19:35
Sorry you're running into this. Can you provide the configuration you're using so I can try and reproduce it?

**Comment by krstivoja** [comment] 2023-10-24 19:53
No worries at all. It is EDD shop and testimonials are CPT. I will try to recreate it as well and upload it somewhere online. Can not share you the current one as I have customers info there. Thanks you for the support and great work by the way.

**Comment by timbowen** [comment] 2023-11-30 23:00
We're running into this same issue which is easy to replicate:

1. Create AQL block with Post meta filters
2. On the same page, create a core Query Loop block 

This shows correctly in the editor, but no matter what settings you change on Query Loop block, it inherits the AQL block settings.

**Comment by timbowen** [comment] 2023-12-01 01:27
I found a quick fix to keep the meta query from being inherited from other blocks:

Add this to **query-loop.php** around line 118, just above // Check for meta queries.

`$query_args['meta_query'] = array(); // Reset meta query so it's not inherited from other blocks.`

This may not be the best solution but it does fix the bug.

**Comment by sstruemph** [comment] 2023-12-06 15:08
@timbowen I've run into the same issue and tried your fix. However it didn't have any effect. Was there a trick to making it work other than adding that line?

**Comment by sstruemph** [comment] 2023-12-06 16:58
I ended up not using this plugin and just altered the query when the Query Loop block is set to a specific CPT. Since I only needed one custom query for that CPT it was easier to just override the query of the block when it is set to a specific CPT.

https://developer.wordpress.org/reference/hooks/query_loop_block_query_vars/#comment-6300

```add_filter('query_loop_block_query_vars', 'wpdocs_filter_query');
function wpdocs_filter_query($query)
{
  // ignore if the query block is not using this post type
  if ('events' !== $query['post_type']) {
    return $query;
  }

  // Set the current date
  $today = date('Ymd');

  // Meta query
  $meta_query = array(
    array(
      'key'     => 'event_start_date',
      'value'   => $today,
      'compare' => '>=',
      'type'    => 'DATE' // Make sure to define the type as DATE
    )
  );

  // Apply the meta query to the main query
  $query['meta_query'] = $meta_query;

  // Override "order by" settings
  $query['orderby'] = array(
    'event_start_date' => 'ASC' // Order by date in ascending order
  );

  return $query;
}

**Comment by ryanwelcher** [comment] 2023-12-19 20:24
Really sorry for the late response here! I was able to replicate this locally and will get a fix together ASAP.

For the record, there were my testing steps:

1. Insert AQL with CPT selected and do a post meta query
2. Insert second AQL instance set to Post
3. Insert a standard Query Loop set to Post

Results: Back end displays OK, nothing in the second or third instance instance on the FE.

**Comment by krstivoja** [comment] 2023-12-29 20:04
Thanks a lot for solving it and sorry for not be able to help with debugging

**Comment by filip-van-hoeckel** [comment] 2024-01-19 10:06
I am sorry to report this is not fixed in the latest version on my end. What am I missing?

**Comment by ryanwelcher** [comment] 2024-01-19 14:41
> I am sorry to report this is not fixed in the latest version on my end. What am I missing?

Would you be able to provide the plugin version number and the settings you're using so I can reproduce this locally?

**Comment by filip-van-hoeckel** [comment] 2024-01-19 15:48
v 2.1.0. What specific settings would you like to know?

**Comment by ryanwelcher** [comment] 2024-01-19 16:09
> What specific settings would you like to know?

How you are setting up the two instances of AQL. Post types, meta queries, ordering etc. I'd like to be able to replicate the issue locally.

**Comment by filip-van-hoeckel** [comment] 2024-01-19 16:52
First loop: CPT 'Team-members': featured image, name, role. Meta query filter for ACF field Organisation where value LIKE <clientname>. Sort order: menu_order.

Second loop: CPT Vacancies: Title, excerpt, sort order: menu_order. No filter.

**Comment by filip-van-hoeckel** [comment] 2024-01-24 08:22
If necessary I can provide a staging site to explore and test.

**Comment by ryanwelcher** [comment] 2024-01-24 19:26
That would be fantastic! Feel free to email me with credentials. I'm will be AFK for the next two weeks so may not be able to look at it until I am back.

**Comment by filip-van-hoeckel** [comment] 2024-02-01 14:51
I have sent you an invite from our staging site, as we're experiencing an issue with a meta query not working on production as well. Thanks in advance.

**Comment by filip-van-hoeckel** [comment] 2024-02-12 14:19
Did you manage to take a look?

**Comment by filip-van-hoeckel** [comment] 2024-02-20 08:32
Well, guess we'll be looking for workaround. Pity; this felt like the missing link.

**Comment by ryanwelcher** [comment] 2024-02-20 13:44
Sorry for the radio silence here, I was away for a couple of weeks. I'll have a look at this today.

**Comment by ryanwelcher** [comment] 2024-02-20 13:50
@filip-van-hoeckel would you resend the credentials please? I'll look ASAP

**Comment by ryanwelcher** [comment] 2024-02-20 14:12
I was able to find the original credentials and have taken a look and am not able to reproduce this issue. That being said, I don't know the data set at all so perhaps I didn't set this up correctly.

In the AQL instance for the team, I added a Post Meta query with the following settings

![Cursor_and_Pagina_bewerken_“De_WMC_familie__het_gaat_niet_alleen_om_wat_we_doen__maar_om_wie_we_zijn_”_‹_Wieck_Molendijk_Consultants_—_WordPress](https://github.com/ryanwelcher/advanced-query-loop/assets/1259027/e23209df-5c99-4a08-a717-ff66902e93ec)

The AQL instance for vacancies was not affected at all and it showed the same content no matter what value I added to the Meta Value field ( even ones that resulted in no team members being shown ).

Can you confirm that I set this up correctly?

If you are stilling running into this, please set up the two instances in that staging instance to show me the issue and I'll take another look!

**Comment by filip-van-hoeckel** [comment] 2024-02-20 14:30
Bizarrely enough, this looks correct, whereas we did experience this issue before, both local as well as on our staging server. Thanks for the effort!

**Comment by ryanwelcher** [comment] 2024-02-20 14:41
I'm glad it's working as expected! I'm going to close this out but if the issue persists, please open a new one.

Thanks again for using the plugin and your patience getting this resolved.

**Closed as completed by ryanwelcher** 2024-02-20 14:41 UTC
Labels: bug
